import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import layout from "@/ui/layout";

const inter = Inter({ subsets: ["latin"] });

const { Wrapper, Conteiner, Header, Footer } = layout;

export const metadata: Metadata = {
  title: "AppointMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Header logo={"AppointMe"}></Header>
          <Conteiner>{children}</Conteiner>
          <Footer>
            <span>Created by @pavlenkodim</span>
            <span>AppointMe ©{new Date().getFullYear()}</span>
          </Footer>
        </Wrapper>
      </body>
    </html>
  );
}
